require_relative '../words'

_3_29 = Words.new

# noinspection RubyStringKeysInHashInspection
_3_29.words ({
		'period' => '一段时间（a ~ of time）',
		'crew' => '有组织的一组人',
		'bulldozer' => '推土机',
		'Vietnam' => '越南',
		'Laos' => '老挝',
		'Cambodia' => '柬埔寨',
		'film' => '拍电影（v.），胶片',
		'coconut palm' => '椰树',
		'tropical' => '热带的',
		'palm tree' => '棕榈树',
		'work' => '起作用',
		'pole' => '长杆，长柱',
		'very good of' => '很多很多',
		# 'for a while' => '暂时',
		'fishing' => '渔业',
		'make money from' => '靠...维生',
		'vegetation' => '植被',
		'level' => '平坦的，等级',
		'put in' => '种植',
		'weak' => '松散的，松动的，稀的',
		'monsoon' => '季风',
		'conspiracy' => '阴谋',
		'even' => '平坦，甚至，偶数',
		'bit' => '一块一块一坨一坨的小玩意',
		'snapshot' => '快照',
		'gem' => '宝石',
		'Pacific Ocean' => '太平洋',
		'pacific' => '平静的，安宁的',
		'pacifist' => '和平主义者',
		'Peru' => '秘鲁',
		'Ecuador' => '厄瓜多尔',
		'high plain' => '高原（两个单词）',
		'plateau' => '高原（一个单词）',
		'coastal' => '海岸的，海边的',
		'recover' => '恢复',
		'form' => '形成',
		'pattern' => '图案',
		'Dutch' => '荷兰的，荷兰人的，荷兰语的',
		'Holland' => '荷兰（音译，不常用）',
		'Netherlands' => '荷兰',
		'volcano' => '火山',
		'present' => '呈现出来',
		'alienate' => '疏离、疏远',
		'tank' => '潭',
		'posts' => '杆子',
		'retarded' => '笨蛋（病理性的）',
		'come over' => '过来',
		'clerk' => '职员',
		'auditorium' => '音乐厅',
		'court' => '法院',
		# 'chef' => '大厨',
		'overall' => '连体套装',
		'collar' => '领子',
		'freelance' => '自由职业（adj.）',
		'freelancer' => '自由职业者',
		"flexitime's" => '弹性时间',
		'temp' => '临时工',
		'airy' => '通风的',
		'labour' => '劳动',
		'outfit' => '装扮，造型',
		'insurance' => '保险',
		'teller' => '（银行）柜员',
		'accessory' => '饰品，附件',
		'grocery' => '杂货',
		'welfare' => '福利',
		'sleep on it' => '留到次日解决',
		"bite one's head off" => '（对某人）暴跳如雷',
		'amuse' => '逗乐',
		'launch' => '发射、发起，发动、启动、新产品发行出版',
		'have a tantrum' => '发脾气，发怒',
		'athletic' => '运动型的，健美♂的',
		'hot-headed' => '易冲动的',
		'regret' => '遗憾，悔恨（n.）',
		'illegible' => '字迹难以辨认的',
		'mythical' => '神话的，虚构的',
		'creepy' => '令人毛骨悚然的',
		'inglorious' => '不光彩的，可耻的',
		'irrational' => '不合理的',
		'elf' => '小精灵',
		'epic' => '史诗',
		'suspense' => '悬念',
		'terrorise' => '使畏惧，恐吓',
		'sit for' => '坐着（让人画像/拍照）',
		'sit out' => '坐观（而不参加）',
		'sit through' => '一直等到...结束',
		'sit back' => '坐等',
		'suspend' => '暂停，终止（由于犯规，犯错等）',
		'suspect' => '怀疑，猜想（v.）嫌疑犯（n.）',
		'deposit' => '存款（v. n.）',
		'feel like doing' => '想做...',
		'feel the need' => '感到有必要',
		'in and out' => '进进出出',
		'on and on' => '没完没了',
		'on the up and up' => '扶摇直上九万里，青云直上，节节攀升',
		'give in' => '屈服',
		'give out' => '散发出某种味道',
})

# _3_29.review
# _3_29.listen_write

define_method :get_today do
	_3_29
end
