require_relative '../words'

_3_28 = Words.new
# noinspection RubyStringKeysInHashInspection
_3_28.words ({
		'autograph' => '亲笔签名',
		"I'm off to sw." => '我要离开去...',
		'be in a panic' => '惊恐，惊慌',
		'stuck' => '粘上去（过去分词）',
		# 'No to start with' => '一开始没有',
		'lift' => '提起来（v.），电梯（n.）',
		'as well' => '也（== too）（句尾）',
		'arson' => '纵火',
		'burglary' => '入室行窃',
		'convicted' => '被判有罪的',
		'pretend' => '假装，后面加虚拟语气',
		'joyriding' => '偷车兜风',
		'pick-pocket' => '扒窃',
		'probation' => '缓刑（n.）',
		'shoplifting' => '入店行窃',
		'vandalism' => '破坏公物',
		'break down' => '出故障',
		'get sb. down' => '使某人沮丧',
		'turn sth. down' => '拒绝某事物',
		'basically' => '差不多（整体上来讲）',
		'boredom' => '厌倦，无聊',
		'owe' => '欠（某人）（钱，东西，人情）',
		'charity' => '慈善',
		'charity box' => '捐款箱',
		'go to church' => '做礼拜',
		'You never know' => '你不试试怎么知道',
		'suppose' => '假设（和think差不多）',
		'survey' => '调查（~ into）',
		'spray' => '喷溅，喷绘（~ painting）',
		'I wish/if only' => '（第二条件句：不可能的事情）',
		'self-sufficient' => '自给自足的',
		'mess' => '把...弄的一团糟',
		'realistic' => '现实的',
		# 'mate' => '朋友伙伴',
		'could have (been) done' => '过去本能怎样，却并没有怎样',
		'mechanic' => '机械师',
		'mechanic engineering' => '机械工程',
		'moon buggy' => '月球车',
		'astronaut' => '宇航员',
		'astronomy' => '航天学',
		'crater' => '火山口',
		'sky' => '天空（广义的）',
		'moon landing' => '登月',
		'therefore' => '因此',
		'fake' => '假的东西，赝品（n.）',
		# "can't be" => '绝对不是',
		'Russians' => '苏联人',
		'mathematics' => '数学',
		'race' => '种族',
		'racial' => '种族的',
		'tan' => '偏黑',
		'full beard' => '络腮胡',
		'dishonest' => '虚伪的',
		'slim' => '瘦',
		'chubby' => '丰满',
		'hostile' => '敌对的，有攻击性的',
		'generous' => '慷慨的',
		'plain-looking' => '贫瘠的外貌',
		'sly' => '狡猾的',
		'indifferent' => '冷漠的',
		'selfless' => '无私的',
		'tense' => '严肃的',
		'character' => '本性（内在的）',
		'characteristic' => '特征（外在的）',
		'personality' => '性格',
		'loyal' => '忠诚的（狗对人忠诚）',
		'versatile' => '多才多艺的',
		'blond' => '金发',
		'how dare you' => '你天大的胆子',
		'considerate' => '考虑周全的',
		'push' => '逼着',
		'discipline' => '纪律',
		'code' => 'rule',
		'mislead' => '误导',
		'bossy' => '霸道',
		'realize the dream' => '实现梦想',
		'ginger' => '红发',
		'zone out' => '神游，开小差',
		'curly' => '小卷卷',
		'wave' => '大波浪',
		'reserved' => '内敛的，不爱说话的',
		'in spite of' => '考虑到',
		# In spite of the material benefits wealth provide,
		# I believe one should abandon the pursuit of materialism
		# and instead concentrate on the pursuit of happiness.
		'wealth' => '财富，富裕',
		'pursuit' => '追求',
		'materialism' => '物质化，物质主义',
		'an idea occurs' => '冒出了一个主意（in my brain, etc.',
		# 'vanish' => '消失',
		'neglect' => '忽略',
		'sort it out' => '== work it out，解决',
		'confidential' => '机密的',
		'desertification' => '沙漠化',
		'extinct' => '绝种的，不复存在的',
		'extinction' => '灭绝',
		'credible' => '可靠的',
		'incredible' => '不可靠的、极好的难以置信的',
		'remote control' => '遥控器',
		'spoiled' => '被溺爱的',
		'made out of' => '由什么制成',
		'inhabit' => '栖息，居住于（v.',
		'inhabitation' => '居住，栖息（n.',
		'undid' => 'undo 过去式',
		'undone' => 'undo 过去分词（解开的，松开的，未完成的，毁掉的）',
		'call off' => '取消',
		'come across' => '偶然发现',
		'extinguish' => '熄灭（一个单词）',
		'pay off' => '成功，使有效',
		'decorative' => '装饰性的',
		'decorator' => '装潢师',
		'decoration' => '装饰品',
		'eternal' => '永恒',
		'holy' => '神圣的，secret也是这个意思',
		'apparition' => '幽灵，鬼怪',
		'archaeologist' => '考古学家',
		'curse' => '咒语（n.）诅咒，咒骂（v.）',
		'destiny' => '命运',
		'destined' => '注定的，必然的',
		'passageway' => '过道',
		'statue' => '雕塑',
		'disturb' => '打扰（v.）',
		'disturbance' => '打扰（n.）',
		'afro' => '非洲式发型',
		'whisker' => '胡茬，面部的胡须',
		'sideburns' => '侧须',
		'goatee' => '山羊胡',
		'bang' => '刘海',
		'temper' => '脾气，性情',
		'determine' => '下定决心',
		# beg for sth.
		# I beg of you 我求你了
		'purity' => '纯度',
		'fiance' => '未婚夫',
		'fiancee' => '未婚妻',
		'bride' => '新娘',
		'bride maid' => '伴娘',
		'groom' => '新郎',
		'spiky' => '（头发）短而直',
		'prayer' => '祷告词',
})

# _3_28.review
_3_28.listen_write
