require_relative '../words'

_3_30 = Words.new
# noinspection RubyStringKeysInHashInspection
_3_30.words ({
		'intensive' => '密集的，加强的',
		'aggressive' => '具有侵略性的',
		'controversial' => '具有争议的',
		'empathy' => '感同身受，移情',
		'systems-thinking' => '系统性思维',
		'flu' => '流感',
		'crisis' => '危机（单数）',
		'crises' => '危机（复数）',
		'fresh water' => '淡水',
		'promote' => '宣传，促进，提高',
		'impoverished' => '贫穷的（书面）',
		'numerous' => '众多的（书面）',
		'Box office' => '票房，售票处',
		'strike' => '擦，蹭，擦过，划过',
		'plump' => '丰满圆胖，偏胖',
		'possess' => '对...具有所有权',
		'whistle' => '吹口哨',
		'gasp' => '喘气',
		'grow' => '种植，使生长（vt.）',
		'vary' => '变化（n.）多变（v.）',
		'spouse' => '配偶（生物上的）',
		'conduct' => '操作，操纵（抽象的）',
		'canopy' => '篝火',
		'priest' => '牧师',
		'eventually' => '最终',
		'resort to' => '诉诸于，凭借于',
		'autistic' => '患自闭症的',
		'diagnose' => '诊断',
		'disorder' => '失调',
		'memorise' => '默记',
		'brainchild' => '想法',
		'brainwave' => '灵感',
		'remarkable' => '值得注意的',
		'forehead' => '前额',
		'suspicion' => '猜疑，怀疑',
		'groan' => '呻吟',
		'squat' => '蹲',
		'stack' => '将某物堆起',
		'wrestle' => '扭打，摔跤',
		'yell' => '喊叫',
		'architecture' => '建筑设计',
		'feature' => '给...以显著位置（v.）',
		'operate' => '做手术（常指外科手术），执行、实行（尤指操作起来比较难的）',
		'operation' => '公司，企业，机构',
})

def_getter _3_30
_3_30.listen_write
