require_relative '../words'


words = [
		'syndrome',
		"take someone's mind off",
		'squat',
		'suspicion',
		'wrestle',
		'yell',
		'immediately',
		'remedy',
		'symptom',
		'therapy',
		'indigenous',
		'herbal',
		'panicky',
		'instructor',
		'diminish',
		'pass down',
		'frankly',
		'easier said than done',
		'how come ...?',
		'harmoniously',
		'amateur',
		'board',
		'ice hockey',
		'short-term',
		'engineering',
		'newborn',
		'charismatic',
		'cult',
		'denial', #{n.}
		'refusal', #{n.}
		'run out of time',
		'convince',
		'tear apart',
		'take time off',
		'overtake',
		'hypocritical',
		'intellectual',
		'pretentious',
		'smug',
		'scruffy',
		'sympathetic',
		'witty',
		'gossip',
]

