# coding: utf-8
require_relative '../words'

take_it_easy = {
		'loosen up' => '放松',
		'entitle ... to do' => '授予某人做...的权利',
		'enpower ... to do' => '给予某人做...的权利',
		'pros and cons' => '优缺点',
		'cuisine' => '菜肴',
		'tense' => '紧张的',
		'steep' => '陡峭的',
		'slope' => '坡，倾斜',
		'urban' => '城市的',
		'overpainting' => '用漆等涂掉',
		'behavioral' => '行为的',
		'contributor' => '捐赠人',
		'carboniferous' => '产碳的',
		'plantation' => '种植园',
		'transplanted' => '移栽',
		'laborious' => '艰巨的，艰难的',
		'exposition' => '详细阐述',
		'composer' => '创作者（作曲家）',
		'galcier' => '冰川',
		'diverse' => '多种多样的',
		'urbanization' => '城市化',
		'construction' => '建造',
		'acorn' => '橡子',
		'democratic' => '民主制度的',
		'stylistic' => '文体上的，风格的',
		'projection' => '',
		'cetaceans' => '',
		'tension' => '',
		'ritual' => '',
		'scholar' => '',
		'fungi' => '',
		'geologic' => '',
		'parlor' => '',
		'hypothisize' => '',
		'dietary' => '',
		'irrigate' => '',
		'distinction' => '用尽，灭绝',
		'timberline' => '',
		'turbine' => '',
		'tone' => '',
		'adoption' => '',
		'analysts' => '',
		'trace' => '',
		'conception' => '',
		'cycle' => '',
		'habitat' => '',
		'reveal' => '',
		'crystalline' => '',
		'canal' => '',
		'timber' => '',
		'tribe' => '',
		'chimpanzee' => '',
}

_5_11 = Words.new
_5_11.words take_it_easy
